#!/usr/bin/env bash
#  Transfers a file from our client to a server using arguments
#+ file path, server IP, username, SSH private key path as paramaters
if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"
fi
