#!/usr/bin/env bash
#  Transfers a file from our client to a server using arguments
#+ file path, server IP, username, SSH private key path as paramaters
if [ "$#" == 4 ]
then
    scp "$1" "$HOME" "$3"@"$2" -i "$4"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
