#!/usr/bin/env bash
# Installing nginx web server
sudo apt-get update -y &&\
sudo apt-get install nginx ufw -y &&\
sudo ufw allow "Nginx HTTP" &&\
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html &&\
sudo service nginx start
exit 0
