#!/usr/bin/env bash
# Redirect to another page
sudo apt-get update -y &&\
sudo apt-get install nginx ufw -y &&\
sudo ufw allow "ssh" &&\
sudo ufw allow "Nginx HTTP" &&\
sudo ufw enable &&\
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	rewrite ^/redirect_me https://github.com/n1klaus permanent;
}"

echo -e "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
exit 0
