#!/usr/bin/env bash
#  Provision a second server and configure custom Nginx response header to track
#+ which web server is answering our HTTP requests

sudo puppet apply puppet_install_nginx_web_server
