#!/usr/bin/env bash
#  Provision a second server and configure custom Nginx response header to track
#+ which web server is answering our HTTP requests
sudo apt-get update -y &&\
sudo apt-get install nginx ufw -y &&\
sudo ufw allow "ssh" &&\
sudo ufw allow "Nginx HTTP" &&\
sudo ufw enable;

mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	rewrite ^/redirect_me https://github.com/n1klaus permanent;
	error_page 404 /404.html;
	add_header X-Served-By $HOSTNAME;
	ignore_invalid_headers on;
}"

echo -e "$SERVER_CONFIG" | sudo tee /etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
exit 0
