#!/usr/bin/env bash
#  Provision and configure a HAproxy load balancer
if [ $(/usr/bin/which puppet | echo $?) != 0 ]
then
	sudo apt update &&\
	sudo apt install ruby &&\
	sudo apt-get install -y ruby-augeas &&\
	sudo apt-get install -y ruby-shadow &&\
	sudo apt-get install -y puppet
fi
sudo puppet apply puppet_configure_haproxy_load_balancer
