#!/usr/bin/env bash
#  Provision and configure a HAproxy load balancer
sudo apt-get update -y &&\
sudo apt-get install haproxy ufw -y &&\
sudo ufw allow "ssh" &&\
sudo ufw allow "80/tcp" &&\
sudo ufw enable

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

echo -e "\nfrontend www\n\tbind *:80\n\tdefault_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend web-backend\n\tmode http\n\tbalance roundrobin\n\tserver 37807-web-01 54.152.232.208:80 check\n\tserver 37807-web-02 54.84.8.157:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

haproxy -c -f /etc/haproxy/haproxy.cfg &&\
sudo service haproxy start
exit 0
