#!/usr/bin/env bash
# Debug server and make sure it is listening on port 80
sudo sed -i --follow-symlinks "s/listen 8080/listen 80/" /etc/nginx/sites-enabled/default
sudo sed -i --follow-symlinks "s/listen \[::\]:8080/listen [::]:80/" /etc/nginx/sites-enabled/default
service nginx restart > /dev/null 2>&1
