#!/usr/bin/env bash
#  This script creates a file in /var/run/ while printing indefinitely
#+ and displays information on SIGTERM, SIGINT, SIGQQUIT signals
MYSCRIPT='/var/run/myscript.pid'
if [ ! -e "$MYSCRIPT" ]
then
    touch "$MYSCRIPT"
fi

echo $$ >> "$MYSCRIPT"

_sig_int()
{
    echo "Y U no love me?!"
}

_sig_quit()
{
    rm /var/run/myscript.pid
    exit
}

_sig_term()
{
    echo "I hate the kill command" && _sig_quit
}

trap _sig_term SIGTERM
trap _sig_quit SIGQUIT
trap _sig_int SIGINT

until [ "$TMOUT" ]; do echo "To infinity and beyond"; sleep 2; done
exit
