#!/usr/bin/env bash
# This script manages manage_my_process
case "$1" in 
    start)
        ./manage_my_process &
        touch /var/run/my_process.pid
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    restart)
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        ./manage_my_process &
        touch /var/run/my_process.pid
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    stop)
        echo "manage_my_process stopped"
        kill "$(cat /var/run/my_process.pid)"
        rm /var/run/my_process.pid
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
exit
