#!/usr/bin/env bash
#  This script displays the PID, along with the process name,
#+ of processes whose name contain the word bash
bash_processes=$(pidof bash)
for p in $bash_processes
do
    echo "$p" bash
done
