#!/usr/bin/env bash
#   This script displays the visitor IP along with the HTTP status code from the
#+  Apache log file and groups visitors by IP and HTTP status code
awk '{print $1 " " $9}' apache-access.log | sort | uniq --count | sort --reverse
