#!/usr/bin/env bash
# This script loops 10 times, prints "bad luck" at 4, "good luck" at 8,
#+"BestSchool" for other iterations
n=0
while [ $(( n++ )) -lt 10 ]
do
    if [ "$n" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$n" -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done
