#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
h=-1
while [ $(( h++ )) ]
do
    m=0
    if [ "$h" -eq 13 ]
    then
        break
    else
        echo "Hour $h"
        while [ $(( m++ )) -lt 60 ]
        do
            if [[ "$m" -eq 60 ]]
            then
                break
            else
                echo "$m"
            fi
        done
    fi
done
