#!/usr/bin/env bash
# This script displays information about the 'school' file
file="school"
if [ ! -e "$file" ]
then
    echo "school file does not exist"
elif [ -e "$file" ]
then
    echo "school file exists"
    if [ ! -s "$file" ]
    then
        echo "school file is empty"
    elif [ -s "$file" ]
    then
        echo "school file is not empty"
    fi

    if [ -f "$file" ]
    then
        echo "school is a regular file"
    fi
fi
