#!/usr/bin/env bash
sudo apt-get -y update &&\
sudo apt-install -y ufw &&\
sudo ufw default deny incoming &&\
sudo ufw allow in "22/tcp" &&\
sudo ufw allow in "80/tcp" &&\
sudo ufw allow in "443/tcp" &&\
sudo enable