#!/usr/bin/env bash
#  This script configures /etc/hosts with the following:
#+ 8.8.8.8 facebook.com 
#+ 127.0.0.2 localhost
NEW_HOSTS="$HOME/new_hosts"
cp /etc/hosts "$NEW_HOSTS"

LH=$(grep -c "$NEW_HOSTS" -e "[^-]localhost")
if [ "$LH" -gt 1 ]
then
    LH_=$(grep -n "$NEW_HOSTS" -e "[^-]localhost" | cut -f 1 -d:)
    DH=$(grep -n "$NEW_HOSTS" -e "127.0.0.1" | cut -f 1 -d:)
    for i in $LH_
    do
        if [ "$DH" -ne "$i" ]
        then
            sed -i "$i"d "$NEW_HOSTS"
        fi
    done
fi

FB=$(grep -c "$NEW_HOSTS" -e "facebook.com")
if [ "$FB" -gt 0 ]
then
    FB_=$(grep -n "$NEW_HOSTS" -e "facebook.com" | cut -f 1 -d:)
    for j in $FB_
    do
        sed -i "$j"d "$NEW_HOSTS"
    done
fi

DNS=$(grep -c "$NEW_HOSTS" -e "8.8.8.8")
if [ "$DNS" -gt 1 ]
then
    DNS_=$(grep -n "$NEW_HOSTS" -e "8.8.8.8" | cut -f 1 -d:)
    for k in $DNS_
    do
        sed -i "$k"d "$NEW_HOSTS"
    done
elif [ "$DNS" -eq 1 ]
then
    NS_=$(grep -n "$NEW_HOSTS" -e "8.8.8.8" | cut -f 2 -d" ")
    sed -i "s/$NS_/facebook.com/" "$NEW_HOSTS"
else
    echo "8.8.8.8 facebook.com" >> "$NEW_HOSTS"
fi

NH=$(grep -c "$NEW_HOSTS" -e "127.0.0.1")
if [ "$NH" -eq 0 ]
then
    echo "127.0.0.2 localhost" >> "$NEW_HOSTS"
else
    sed -i s/127.0.0.1/127.0.0.2/g "$NEW_HOSTS"
fi

sudo cp "$NEW_HOSTS" /etc/hosts
