#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine
ifconfig | grep -oE "inet \b(25[0-5]|2[0-4][0-9]|1?[0-9][0-9]?\.){3}\
(25[0-4]|2[0-4][0-9]|1?[0-9][0-9]?)\b" | cut -f 2 -d" "
