#!/usr/bin/env bash
#  Add a public key for authorized access to the server
#+ from the command line argument
echo "$1" | ssh -v ubuntu@54.152.232.208\
	"mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
